### PR TITLE
181759992 displaying and adding tasks

### PR DESCRIPTION
**Pull request by simonjov**

### CODE REVIEW

**Comment by simonjov** [comment]
lgtm

**Comment by adityasingh7311** [comment]
config/application.yml should not have been pushed

I would remove the unnecessary change in app/controllers/announcements_controller.rb so the PR doesn't include unneccesary files

I don't think the user.rb model should have been part of this PR? The populate function is outdated.

Is it necessary to add empty files like user_controller.rb and user_helper.rb?

Also the entire test directory should not exist. The only tests we have should be cucmber tests in features directory and rspec tests in the spec directory

**Comment by adityasingh7311** [comment]
There's also an empty file app/views/tasks/index-test.html.erb which probably should not have been pushed?

**Comment by adityasingh7311** [comment]
Also in tasks_controller.rb:37 it seems that `def new; end`  is all one line. I don't think that's proper ruby convention?

**Comment by adityasingh7311** [comment]
LGTM

**Pull request merged**
