### PR TITLE
181708826 airtable user populate

### PR DESCRIPTION
**Pull request by adityasingh7311**
Added method to user model that can populate User model db table with records from Airtable. Simple corresponding unit test. 

config/application.yml must be decrypted to be used locally. Need to add secrets to Heroku and Travis CI. Also push gitignore for config/application.yml next time

### CODE REVIEW

**Comment by adityasingh7311** [comment]
I think this should be merged after the first pull request to the golden repo is made to reduce the amount of code in initial pull

**Comment by simonjov** [comment]
lgtm

**Comment by andrewmopro** [comment]
LG2M2

**Comment by andrewmopro** [comment]
LG2M2

**Pull request merged**
